# config/packages/messenger.yaml
framework:
    messenger:
        failure_transport: failed

        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

                retry_strategy:
                    max_retries: 0
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                    jitter: 0.1

            failed: 'doctrine://default?queue_name=failed'
